# @package _group_
type: rnn
state_size: 8
k_size: 32
num_layers: 1
train_pred_len: 60 # The length for calculating loss. It is recommended to be equal to config.forward_length. At least, it should be bigger than config.forward_length + config.history_length



