random_seed: 0
use_cuda: yes
mode: train
sample_tp: 1
save_dir: tmp
ct_time: no
sp: 0.5
base_tp: 0.1
sp_even: no
ctrl_solution: 1
use_model_dataset_config: no
train:
  epochs: 800
  max_epochs_stop: 80  # 50
  batch_size: 512
  eval_epochs: 10
  num_workers: 8
  kl_inc: true
  kl_wait: 10
  kl_max: 1.0
  min_epochs: 200

test:
  plt_cnt: 20
  test_dir: ~
  batch_size: 128
  n_traj : 128
  plt_n_traj: 4
  plt_single: no
  sp_change: no

defaults:
  - model: vaecl
  - train/optim: adam
  - train/schedule: val_step
  - dataset: winding

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - dataset
          - save_dir
          - model.type
          - model
  run:
    dir: ckpt/${dataset.type}/ct_${ct_time}/${save_dir}/${model.type}_${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ckpt/${dataset.type}/ct_${ct_time}/${save_dir}
    subdir: ${model.type}_${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
