random_seed: ~
use_cuda: yes
mode: train
history_length: 180
forward_length: 60
save_dir: tmp
train:
    epochs: 800
    max_epochs_stop: 100
    batch_size: 256
    eval_epochs: 10
    num_workers: 8

test:
    plt_cnt: 20
    test_dir: ~
    batch_size: 32

defaults:
    - model: vrnn
    - train/optim: adam
    - train/schedule: exp
    - dataset: southeast

hydra:
    job:
        config:
            override_dirname:
              exclude_keys:
                - dataset
                - save_dir
                - model.type
                - model
    run:
        dir: ckpt/${dataset.type}/${save_dir}/${model.type}_${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
        dir: ckpt/${dataset.type}/${save_dir}
        subdir: ${model.type}_${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
