random_seed: ~
use_cuda: yes
mode: train
sample_tp: 1
history_length: 180
forward_length: 60
save_dir: tmp
ct_time: no
sp: 0.5
base_tp: 0.1
ctrl_solution: 1
train:
  epochs: 800
  max_epochs_stop: 100
  batch_size: 512
  eval_epochs: 10
  num_workers: 8

test:
  plt_cnt: 20
  test_dir: ~
  batch_size: 128

defaults:
  - model: vaecl
  - train/optim: adam
  - train/schedule: exp
  - dataset: southeast

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - dataset
          - save_dir
          - model.type
          - model
  run:
    dir: ckpt/${dataset.type}/ct_${ct_time}/${save_dir}/${model.type}_${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ckpt/${dataset.type}/${save_dir}
    subdir: ${model.type}_${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
