type: ballbeam
input_size: 1
observation_size: 1
dataset_window: 2
train_path: data/ballbeam/ballbeam_train.csv
val_path: data/ballbeam/ballbeam_val.csv
test_path: data/ballbeam/ballbeam_test.csv
target_names: ['1']
history_length: 20
forward_length: 60