# @package _group_
type: ib
input_size: 3
observation_size: 6
dataset_window: 5
train_path: data/ib/ibState_train_1.csv
val_path: data/ib/ibState_val_1.csv
test_path: data/ib/ibState_test_1.csv
target_names: ['v', 'g', 'h', 'fatigue', 'consumption', 'reward']