# @package _group_
type: nl
input_size: 1
observation_size: 1
dataset_window: 2000
train_path: data/nl/narendra_li_train_1.csv
val_path: data/nl/narendra_li_val_1.csv
test_path: data/nl/narendra_li_test_1.csv
target_names: ['y']
history_length: 1
forward_length: 1999