model: ib_vrnn_5_1026.pkl # ckpt path of planning model.
cuda: 0 # GPU ID, -1 for CPU
input_dim: 3 # Dimension of system input
output_dim: 6 # Dimension of system output
init_action: [50 , 50 , 50]
controlled_ids: all # The controlled ids in outputs, all or [a1,a2..am] 0<=ai<output_dim.
default_set_point: [-10, -10, 10] # The size of set_point should be equal to controlled_ids
debug: False
port: 6010 # The port of controlling service
defaults:
  - algorithm: cem # Controlling algorithm
